import { gql } from "@apollo/client";
import { GroupDetails, PublicKeyDetails } from "@chatTypes";
import { store } from "@chatStore/index";
import { client } from "./client";
import {
  Group,
  leaveGroupMutation,
  UpdateGroupLastSeen,
  UpdatePublicKey,
} from "./groups-queries";

export const updatePublicKey = async (publicKeyDetails: PublicKeyDetails) => {
  const state = store.getState();
  const { data, errors } = await client.mutate({
    mutation: gql(UpdatePublicKey),
    fetchPolicy: "no-cache",
    context: {
      headers: {
        Authorization: `Bearer ${state.user.accessToken}`,
      },
    },
    variables: {
      publicKeyDetails,
    },
  });

  if (errors) console.log("errors", errors);
  return data.updatePublicKey;
};

export const createGroup = async (groupDetails: GroupDetails) => {
  const state = store.getState();

  try {
    const { data, errors } = await client.mutate({
      mutation: gql(Group),
      fetchPolicy: "no-cache",
      context: {
        headers: {
          Authorization: `Bearer ${state.user.accessToken}`,
        },
      },
      variables: { groupDetails },
    });
    if (errors) {
      return {
        type: "Group",
        message: errors || "Something went wrong, Group can't be created",
        level: 1,
      };
    }
    return data.group;
  } catch (e: any) {
    return {
      type: "Group",
      message: e?.message || "Something went wrong, Group can't be created",
      level: 1,
    };
    return null;
  }
};

export const leaveGroup = async (groupId: string) => {
  const state = store.getState();

  try {
    const { data, errors } = await client.mutate({
      mutation: gql(leaveGroupMutation),
      fetchPolicy: "no-cache",
      context: {
        headers: {
          Authorization: `Bearer ${state.user.accessToken}`,
        },
      },
      variables: { groupId },
    });
    if (errors) {
      return {
        type: "Group",
        message: errors || "Something went wrong, Group can't be left",
        level: 1,
      };
    }
    return data;
  } catch (e: any) {
    return {
      type: "Group",
      message: e?.message || "Something went wrong, Group can't be left",
      level: 1,
    };
  }
};

export const deleteGroup = async (groupId: string) => {
  const state = store.getState();

  try {
    const { data, errors } = await client.mutate({
      mutation: gql(`mutation Mutation($groupId: String) {
        deleteGroup(groupId: $groupId)
      }`),
      fetchPolicy: "no-cache",
      context: {
        headers: {
          Authorization: `Bearer ${state.user.accessToken}`,
        },
      },
      variables: { groupId },
    });
    if (errors) {
      return {
        type: "Group",
        message: errors || "Something went wrong, Group can't be deleted",
        level: 1,
      };
    }
    return data.group;
  } catch (e: any) {
    return {
      type: "Group",
      message: e?.message || "Something went wrong, Group can't be deleted",
      level: 1,
    };
  }
};

//already generated by vinay
export const updateGroupLastSeen = async (
  groupId: string,
  lastSeenTimestamp: string
) => {
  const state = store.getState();
  const { data, errors } = await client.mutate({
    mutation: gql(UpdateGroupLastSeen),
    fetchPolicy: "no-cache",
    context: {
      headers: {
        Authorization: `Bearer ${state.user.accessToken}`,
      },
    },
    variables: { groupId, lastSeenTimestamp },
  });
  if (errors) console.log("errors", errors);
  return data.updateGroupLastSeen;
};
